### ISSUE TITLE
Error displaying multiple reviews for an item

### ISSUE THREAD

**Issue by carlos-sanchez** [beachboyslegacy/beachboyslegacy.github.com#44]
I added new reviews to the surfin-safari item on the surfin-safari-reviews branch. But only the latest review in the array is being displayed. There must be some error with the for loop in album.html.jinja2 or in the data.json but I am unable to find it. Funny thing is that I tested multiple reviews when I first introduced them and they worked fine so it's probably some stupid mistake I can't see. Would you mind taking a look @gfiorav?

**Comment by gfiorav** [comment]
This was fixed! Wrong struct in json :)
