### ISSUE TITLE
Get rating from widgetpack to insert in structured data json

### ISSUE THREAD

**Issue by carlos-sanchez** [beachboyslegacy/beachboyslegacy.github.com#58]
API documentation: https://widgetpack.com/api/rating

API call: https://app.widgetpack.com/widget/rating/bootstrap?id=2265&chan=on-tour-1968

The rating must be inserted in the JSON structured data using this property:

`"aggregateRating": "",`

**Comment by gfiorav** [comment]
Let's close this until we figure out the issues with SEO
